defaults:
  - _self_
  - agent: bc
  - suite: libero
  - dataloader: libero
  - override hydra/launcher: submitit_local

# Root Dir
root_dir: '/home/siddhant/github/retrieval'

# misc
seed: 2
device: cuda
save_video: true
save_train_video: false
use_tb: true
batch_size: 32 #8 #64

# experiment
obs_type: 'pixels' # pixels, features
num_demos_per_task: 10
encoder_type: 'resnet' # base, patch, resnet
policy_type: 'gpt' # mlp, gpt
policy_head: gmm # deterministic, gmm
use_proprio: true
use_language: false
use_actions: false
prompt: text # null, text, goal, episode, subsample_X (X is subsample ratio)
ssl: False
experiment: eval_KITCHEN_SCENE10_close_the_top_drawer_of_the_cabinet

# action chunking
temporal_agg: true # aggregate actions over time
num_queries: 10

# expert dataset
expert_dataset: ${dataloader.bc_dataset}

# Load weights
snapshot: /home/siddhant/github/holodex-v2-policies/bc/exp_local/2024.01.22/145531_KITCHEN_SCENE10_close_the_top_drawer_of_the_cabinet/snapshot.pt

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
  sweep:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    tasks_per_node: 1
    nodes: 1
    submitit_folder: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}/.slurm
