# @package suite
defaults:
  - _self_
  - libero_task: libero_90

suite: libero
name: 'libero'

dataset_fn:
  _target_: read_data.libero.LiberoDataset
  path: '/home/siddhant/github/retrieval/expert_demos/libero'
  suites: ${suite.libero_task.suites}
  task_name: ${suite.libero_task.tasks}
  obs_type: ${obs_type}
  # ssl: false
  history: ${suite.history}
  history_len: ${suite.history_len}
  prompt: ${prompt}
  temporal_agg: ${temporal_agg}
  num_queries: ${num_queries}


# task settings
frame_stack: 1
action_repeat: 1
discount: 0.99
hidden_dim: 512

# train settings
num_train_steps: 2000010
log_every_steps: 100
save_every_steps: 5000
history: true
history_len: 10

# eval
eval_every_steps: 1000
num_eval_episodes: 3
eval_history_len: 5

# obs_keys
pixel_keys: ['pixels','pixels_egocentric']
proprio_key: 'proprioceptive'
feature_key: 'features'

# snapshot
save_snapshot: true

task_make_fn:
  _target_: suite.libero.make
  suites: ${suite.libero_task.suites}
  task_names: ${suite.libero_task.tasks}
  frame_stack: ${suite.frame_stack}
  action_repeat: ${suite.action_repeat}
  seed: ${seed}
  height: 128
  width: 128
  max_episode_len: ??? # to be specified later
  max_state_dim: ??? # to be specified later