# @package suite
defaults:
  - _self_
  - metaworld_task@_global_: hammer

suite: metaworld
name: 'metaworld'

dataset_fn:
  _target_: read_data.metaworld.MetaworldDataset
  dataset_path: '${root_dir}/expert_demos/metaworld'
  task_name: ${task_name}
  num_demos: 1
  obs_type: ${obs_type}
  history: ${suite.history}
  history_len: ${suite.history_len}
  prompt: ${prompt}
  temporal_agg: ${temporal_agg}
  num_queries: ${num_queries}


# task settings
frame_stack: 1
action_repeat: 2
hidden_dim: 1024

# train settings
num_train_steps: 1100000 #110000 #1100000
log_every_steps: 1000
save_every_steps: 20000
history: false
history_len: 10

# eval
eval_every_steps: 1000 #20000
num_eval_episodes: 10
eval_history_len: 5

# for rl
discount: 0.99
num_seed_steps: 12000

# obs_keys
pixel_keys: ['pixels']
proprio_key: ''
feature_key: 'features'

# snapshot
save_snapshot: true

task_make_fn:
  _target_: suite.metaworld.make
  names: ${task_name}
  frame_stack: ${suite.frame_stack}
  action_repeat: ${suite.action_repeat}
  seed: ${seed}
  max_episode_len: ??? # to be specified later
  max_state_dim: ??? # to be specified later
