defaults:
  - _self_
  - agent: bc
  - suite: metaworld
  - override hydra/launcher: submitit_local

# Root Dir
root_dir: '/home/xyz/github/Libero-sim-policies'

# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: true
batch_size: 128

# experiment
obs_type: 'pixels' # pixels, features
encoder_type: 'base' # base, patch, resnet
policy_type: 'mlp' # mlp, gpt
policy_head: gmm # deterministic, gmm
use_proprio: false
prompt: null # null, text, goal, episode, subsample_X (X is subsample ratio)
experiment: debug #mw_bc_hammer_train_encoder

# action chunking
temporal_agg: false # aggregate actions over time
num_queries: 10

# expert dataset
expert_dataset: ${suite.dataset_fn}

# Load weights
load_bc: false
bc_weight: /path/to/bc/weight

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
  sweep:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    tasks_per_node: 1
    nodes: 1
    submitit_folder: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}/.slurm
