bc_dataset:
  _target_: read_data.libero.BCDataset
  # path: '${root_dir}/expert_demos/libero_with_langemb'
  path: /home/siddhant/github/Holo-Bot/extracted_data/clean_data
  suites: ${suite.libero_task.suites}
  task_name: ${suite.libero_task.tasks}
  num_demos_per_task: ${num_demos_per_task}
  obs_type: ${obs_type}
  history: ${suite.history}
  history_len: ${suite.history_len}
  prompt: ${prompt}
  temporal_agg: ${temporal_agg}
  num_queries: ${num_queries}
  img_size: 128
  subsample: 10
